
server:
  port: 8080

spring:
  application:
    name: biography-profile
  datasource:
    url: jdbc:mysql://localhost:3306/profile
    username: root
    password: admin

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: none
    show-sql: true

  flyway:
    locations:
      classpath: db/migration

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka