CREATE TABLE profile (
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(70) NOT NULL,
    age INT(2) NOT NULL,
    biography VARCHAR(300),
    email VARCHAR(150),
    contact VARCHAR(15),
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


